### ISSUE TITLE
NaN value in any coin breaks total display

### ISSUE THREAD

**Issue by weirdr** [Alevale/coingathererextension#1]
When the value of a coin cannot be found a value of $NaN is returned and during the totaling at the top bar the total value of all coins is not displayed.
![image](https://user-images.githubusercontent.com/31463153/34119766-33d41380-e3d8-11e7-8d68-9c255075c788.png)

**Comment by Alevale** [comment]
I'll take a look today (I'll start with this in 9,5 hours from now)

**Comment by weirdr** [comment]
Thanks sir looks good! Awesome addon!

**Comment by uprise88** [comment]
Awesome extension for chrome! Thx for your work Alevale
