### ISSUE TITLE
Digibyte-Skein

### ISSUE THREAD

**Issue by whiteskate** [Alevale/coingathererextension#4]
Hi,  any chance of getting Digibyte-skein added to the list?  Thank you in advance.

**Comment by Alevale** [comment]
Sorry for not replying before, I didn't get an alert, and couldn't see this.

I'll be adding it in the following days!

Hope you enjoy it!

PS: I was on holidays for the past 2 weeks 😄

**Comment by Alevale** [comment]
This should be fixed by #7
